server:
  port: 8082

feign:
  client:
    config:
      default:
        conenctTimeout: 5000
        readTimeout: 5000

logging.level.com.feign.project2.repository.*: DEBUG

sample:
  client:
    url: "http://localhost:8081/user"